### ISSUE TITLE
File and line number not showing, in spite of setting being turned on

### ISSUE THREAD

**Issue by dynamodan** [ngocphamm/jfirephp-3.x#1]
The plugin works nicely, except the file and line number isn't showing in the console, and it's not being included in the firebug header either.  See screenshots.  First screenshot is of chrome network console's header view, second is the joomla setting in adminisrator.

![AltText](http://imagizer.imageshack.com/img924/6660/V7DplW.png)

![AltText](http://imagizer.imageshack.com/img922/1776/rbTmln.png)

**Comment by ngocphamm** [comment]
Sorry I haven't been using this for quite a while now so I'm not sure if I can maintain it or not.

Anyway what extension on Chrome did you use for this? I remember Firebug and FirePHP addons are required on Firefox for this, and now FirePHP addon is not compatible anymore.

**Comment by ngocphamm** [comment]
Hey @dynamodan, I think i fixed it.

**Comment by dynamodan** [comment]
That did fix it, thank you very much!  BTW this git repo was the closest I could identify as being the actively maintained version of jfirephp.  Is there a more "official" one?

**Comment by ngocphamm** [comment]
I don't know of any "official" maintenance of the plugin and that's probably why I created this. I can't really call this "actively maintained" as well. No important updates for the last 5 years until you brought something up ✊️
